USE Monitoramento
GO

--Insert Paises
INSERT INTO Paises VALUES ('Afeganistão','AF','AFG','004')
INSERT INTO Paises VALUES ('África do Sul','ZA','ZAF','710')
INSERT INTO Paises VALUES ('Åland, Ilhas','AX','ALA','248')
INSERT INTO Paises VALUES ('Albânia','AL','ALB','008')
INSERT INTO Paises VALUES ('Alemanha','DE','DEU','276')
INSERT INTO Paises VALUES ('Andorra','AD','AND','020')
INSERT INTO Paises VALUES ('Angola','AO','AGO','024')
INSERT INTO Paises VALUES ('Anguilla','AI','AIA','660')
INSERT INTO Paises VALUES ('Antárctida','AQ','ATA','010')
INSERT INTO Paises VALUES ('Antigua e Barbuda','AG','ATG','028')
INSERT INTO Paises VALUES ('Antilhas Holandesas','AN','ANT','530')
INSERT INTO Paises VALUES ('Arábia Saudita','SA','SAU','682')
INSERT INTO Paises VALUES ('Argélia','DZ','DZA','012')
INSERT INTO Paises VALUES ('Argentina','AR','ARG','032')
INSERT INTO Paises VALUES ('Arménia','AM','ARM','051')
INSERT INTO Paises VALUES ('Aruba','AW','ABW','533')
INSERT INTO Paises VALUES ('Austrália','AU','AUS','036')
INSERT INTO Paises VALUES ('Áustria','AT','AUT','040')
INSERT INTO Paises VALUES ('Azerbeijão','AZ','AZE','031')
INSERT INTO Paises VALUES ('Bahamas','BS','BHS','044')
INSERT INTO Paises VALUES ('Bahrain','BH','BHR','048')
INSERT INTO Paises VALUES ('Bangladesh','BD','BGD','050')
INSERT INTO Paises VALUES ('Barbados','BB','BRB','052')
INSERT INTO Paises VALUES ('Bélgica','BE','BEL','056')
INSERT INTO Paises VALUES ('Belize','BZ','BLZ','084')
INSERT INTO Paises VALUES ('Benin','BJ','BEN','204')
INSERT INTO Paises VALUES ('Bermuda','BM','BMU','060')
INSERT INTO Paises VALUES ('Bielo-Rússia','BY','BLR','112')
INSERT INTO Paises VALUES ('Bolívia','BO','BOL','068')
INSERT INTO Paises VALUES ('Bósnia-Herzegovina','BA','BIH','070')
INSERT INTO Paises VALUES ('Botswana','BW','BWA','072')
INSERT INTO Paises VALUES ('Bouvet, Ilha','BV','BVT','074')
INSERT INTO Paises VALUES ('Brasil','BR','BRA','076')
INSERT INTO Paises VALUES ('Brunei','BN','BRN','096')
INSERT INTO Paises VALUES ('Bulgária','BG','BGR','100')
INSERT INTO Paises VALUES ('Burkina Faso','BF','BFA','854')
INSERT INTO Paises VALUES ('Burundi','BI','BDI','108')
INSERT INTO Paises VALUES ('Butão','BT','BTN','064')
INSERT INTO Paises VALUES ('Cabo Verde','CV','CPV','132')
INSERT INTO Paises VALUES ('Cambodja','KH','KHM','116')
INSERT INTO Paises VALUES ('Camarões','CM','CMR','120')
INSERT INTO Paises VALUES ('Canadá','CA','CAN','124')
INSERT INTO Paises VALUES ('Cayman, Ilhas','KY','CYM','136')
INSERT INTO Paises VALUES ('Cazaquistão','KZ','KAZ','398')
INSERT INTO Paises VALUES ('Centro-africana, República','CF','CAF','140')
INSERT INTO Paises VALUES ('Chade','TD','TCD','148')
INSERT INTO Paises VALUES ('Checa, República','CZ','CZE','203')
INSERT INTO Paises VALUES ('Chile','CL','CHL','152')
INSERT INTO Paises VALUES ('China','CN','CHN','156')
INSERT INTO Paises VALUES ('Chipre','CY','CYP','196')
INSERT INTO Paises VALUES ('Christmas, Ilha','CX','CXR','162')
INSERT INTO Paises VALUES ('Cocos, Ilhas','CC','CCK','166')
INSERT INTO Paises VALUES ('Colômbia','CO','COL','170')
INSERT INTO Paises VALUES ('Comores','KM','COM','174')
INSERT INTO Paises VALUES ('Congo, República do','CG','COG','178')
INSERT INTO Paises VALUES ('Congo, República Democrática do (antigo Zaire)','CD','COD','180')
INSERT INTO Paises VALUES ('Cook, Ilhas','CK','COK','184')
INSERT INTO Paises VALUES ('Coreia do Sul','KR','KOR','410')
INSERT INTO Paises VALUES ('Coreia, República Democrática da (Coreia do norte)','KP','PRK','408')
INSERT INTO Paises VALUES ('Costa do Marfim','CI','CIV','384')
INSERT INTO Paises VALUES ('Costa Rica','CR','CRI','188')
INSERT INTO Paises VALUES ('Croácia','HR','HRV','191')
INSERT INTO Paises VALUES ('Cuba','CU','CUB','192')
INSERT INTO Paises VALUES ('Dinamarca','DK','DNK','208')
INSERT INTO Paises VALUES ('Djibouti','DJ','DJI','262')
INSERT INTO Paises VALUES ('Dominica','DM','DMA','212')
INSERT INTO Paises VALUES ('Dominicana, República','DO','DOM','214')
INSERT INTO Paises VALUES ('Egipto','EG','EGY','818')
INSERT INTO Paises VALUES ('El Salvador','SV','SLV','222')
INSERT INTO Paises VALUES ('Emiratos Árabes Unidos','AE','ARE','784')
INSERT INTO Paises VALUES ('Equador','EC','ECU','218')
INSERT INTO Paises VALUES ('Eritreia','ER','ERI','232')
INSERT INTO Paises VALUES ('Eslováquia','SK','SVK','703')
INSERT INTO Paises VALUES ('Eslovénia','SI','SVN','705')
INSERT INTO Paises VALUES ('Espanha','ES','ESP','724')
INSERT INTO Paises VALUES ('Estados Unidos da América','US','USA','840')
INSERT INTO Paises VALUES ('Estónia','EE','EST','233')
INSERT INTO Paises VALUES ('Etiópia','ET','ETH','231')
INSERT INTO Paises VALUES ('Faroe, Ilhas','FO','FRO','234')
INSERT INTO Paises VALUES ('Fiji','FJ','FJI','242')
INSERT INTO Paises VALUES ('Filipinas','PH','PHL','608')
INSERT INTO Paises VALUES ('Finlândia','FI','FIN','246')
INSERT INTO Paises VALUES ('França','FR','FRA','250')
INSERT INTO Paises VALUES ('Gabão','GA','GAB','266')
INSERT INTO Paises VALUES ('Gâmbia','GM','GMB','270')
INSERT INTO Paises VALUES ('Gana','GH','GHA','288')
INSERT INTO Paises VALUES ('Geórgia','GE','GEO','268')
INSERT INTO Paises VALUES ('Geórgia do Sul e Sandwich do Sul, Ilhas','GS','SGS','239')
INSERT INTO Paises VALUES ('Gibraltar','GI','GIB','292')
INSERT INTO Paises VALUES ('Grécia','GR','GRC','300')
INSERT INTO Paises VALUES ('Grenada','GD','GRD','308')
INSERT INTO Paises VALUES ('Gronelândia','GL','GRL','304')
INSERT INTO Paises VALUES ('Guadeloupe','GP','GLP','312')
INSERT INTO Paises VALUES ('Guam','GU','GUM','316')
INSERT INTO Paises VALUES ('Guatemala','GT','GTM','320')
INSERT INTO Paises VALUES ('Guernsey','GG','GGY','831')
INSERT INTO Paises VALUES ('Guiana','GY','GUY','328')
INSERT INTO Paises VALUES ('Guiana Francesa','GF','GUF','254')
INSERT INTO Paises VALUES ('Guiné-Bissau','GW','GNB','624')
GO	   
INSERT INTO Paises VALUES ('Guiné Equatorial','GQ','GNQ','226')
INSERT INTO Paises VALUES ('Guiné-Conacri','GN','GIN','324')
INSERT INTO Paises VALUES ('Haiti','HT','HTI','332')
INSERT INTO Paises VALUES ('Heard e Ilhas McDonald, Ilha','HM','HMD','334')
INSERT INTO Paises VALUES ('Honduras','HN','HND','340')
INSERT INTO Paises VALUES ('Hong Kong','HK','HKG','344')
INSERT INTO Paises VALUES ('Hungria','HU','HUN','348')
INSERT INTO Paises VALUES ('Iémen','YE','YEM','887')
INSERT INTO Paises VALUES ('Índia','IN','IND','356')
INSERT INTO Paises VALUES ('Indonésia','ID','IDN','360')
INSERT INTO Paises VALUES ('Iraque','IQ','IRQ','368')
INSERT INTO Paises VALUES ('Irão','IR','IRN','364')
INSERT INTO Paises VALUES ('Irlanda','IE','IRL','372')
INSERT INTO Paises VALUES ('Islândia','IS','ISL','352')
INSERT INTO Paises VALUES ('Israel','IL','ISR','376')
INSERT INTO Paises VALUES ('Itália','IT','ITA','380')
INSERT INTO Paises VALUES ('Jamaica','JM','JAM','388')
INSERT INTO Paises VALUES ('Japão','JP','JPN','392')
INSERT INTO Paises VALUES ('Jersey','JE','JEY','832')
INSERT INTO Paises VALUES ('Jordânia','JO','JOR','400')
INSERT INTO Paises VALUES ('Kiribati','KI','KIR','296')
INSERT INTO Paises VALUES ('Kuwait','KW','KWT','414')
INSERT INTO Paises VALUES ('Laos','LA','LAO','418')
INSERT INTO Paises VALUES ('Lesoto','LS','LSO','426')
INSERT INTO Paises VALUES ('Letónia','LV','LVA','428')
INSERT INTO Paises VALUES ('Líbano','LB','LBN','422')
INSERT INTO Paises VALUES ('Libéria','LR','LBR','430')
INSERT INTO Paises VALUES ('Líbia','LY','LBY','434')
INSERT INTO Paises VALUES ('Liechtenstein','LI','LIE','438')
INSERT INTO Paises VALUES ('Lituânia','LT','LTU','440')
INSERT INTO Paises VALUES ('Luxemburgo','LU','LUX','442')
INSERT INTO Paises VALUES ('Macau','MO','MAC','446')
INSERT INTO Paises VALUES ('Macedónia, República da','MK','MKD','807')
INSERT INTO Paises VALUES ('Madagáscar','MG','MDG','450')
INSERT INTO Paises VALUES ('Malásia','MY','MYS','458')
INSERT INTO Paises VALUES ('Malawi','MW','MWI','454')
INSERT INTO Paises VALUES ('Maldivas','MV','MDV','462')
INSERT INTO Paises VALUES ('Mali','ML','MLI','466')
INSERT INTO Paises VALUES ('Malta','MT','MLT','470')
INSERT INTO Paises VALUES ('Malvinas, Ilhas (Falkland)','FK','FLK','238')
INSERT INTO Paises VALUES ('Man, Ilha de','IM','IMN','833')
INSERT INTO Paises VALUES ('Marianas Setentrionais','MP','MNP','580')
INSERT INTO Paises VALUES ('Marrocos','MA','MAR','504')
INSERT INTO Paises VALUES ('Marshall, Ilhas','MH','MHL','584')
INSERT INTO Paises VALUES ('Martinica','MQ','MTQ','474')
INSERT INTO Paises VALUES ('Maurícia','MU','MUS','480')
INSERT INTO Paises VALUES ('Mauritânia','MR','MRT','478')
INSERT INTO Paises VALUES ('Mayotte','YT','MYT','175')
INSERT INTO Paises VALUES ('Menores Distantes dos Estados Unidos, Ilhas','UM','UMI','581')
INSERT INTO Paises VALUES ('México','MX','MEX','484')
INSERT INTO Paises VALUES ('Myanmar (antiga Birmânia)','MM','MMR','104')
INSERT INTO Paises VALUES ('Micronésia, Estados Federados da','FM','FSM','583')
INSERT INTO Paises VALUES ('Moçambique','MZ','MOZ','508')
INSERT INTO Paises VALUES ('Moldávia','MD','MDA','498')
INSERT INTO Paises VALUES ('Mónaco','MC','MCO','492')
INSERT INTO Paises VALUES ('Mongólia','MN','MNG','496')
INSERT INTO Paises VALUES ('Montenegro','ME','MNE','499')
INSERT INTO Paises VALUES ('Montserrat','MS','MSR','500')
INSERT INTO Paises VALUES ('Namíbia','NA','NAM','516')
INSERT INTO Paises VALUES ('Nauru','NR','NRU','520')
INSERT INTO Paises VALUES ('Nepal','NP','NPL','524')
INSERT INTO Paises VALUES ('Nicarágua','NI','NIC','558')
INSERT INTO Paises VALUES ('Níger','NE','NER','562')
INSERT INTO Paises VALUES ('Nigéria','NG','NGA','566')
INSERT INTO Paises VALUES ('Niue','NU','NIU','570')
INSERT INTO Paises VALUES ('Norfolk, Ilha','NF','NFK','574')
INSERT INTO Paises VALUES ('Noruega','NO','NOR','578')
INSERT INTO Paises VALUES ('Nova Caledónia','NC','NCL','540')
INSERT INTO Paises VALUES ('Nova Zelândia (Aotearoa)','NZ','NZL','554')
INSERT INTO Paises VALUES ('Oman','OM','OMN','512')
INSERT INTO Paises VALUES ('Países Baixos (Holanda)','NL','NLD','528')
INSERT INTO Paises VALUES ('Palau','PW','PLW','585')
INSERT INTO Paises VALUES ('Palestina','PS','PSE','275')
INSERT INTO Paises VALUES ('Panamá','PA','PAN','591')
INSERT INTO Paises VALUES ('Papua-Nova Guiné','PG','PNG','598')
INSERT INTO Paises VALUES ('Paquistão','PK','PAK','586')
INSERT INTO Paises VALUES ('Paraguai','PY','PRY','600')
INSERT INTO Paises VALUES ('Peru','PE','PER','604')
INSERT INTO Paises VALUES ('Pitcairn','PN','PCN','612')
INSERT INTO Paises VALUES ('Polinésia Francesa','PF','PYF','258')
INSERT INTO Paises VALUES ('Polónia','PL','POL','616')
INSERT INTO Paises VALUES ('Porto Rico','PR','PRI','630')
INSERT INTO Paises VALUES ('Portugal','PT','PRT','620')
INSERT INTO Paises VALUES ('Qatar','QA','QAT','634')
INSERT INTO Paises VALUES ('Quénia','KE','KEN','404')
INSERT INTO Paises VALUES ('Quirguistão','KG','KGZ','417')
INSERT INTO Paises VALUES ('Reino Unido da Grã-Bretanha e Irlanda do norte','GB','GBR','826')
INSERT INTO Paises VALUES ('Reunião','RE','REU','638')
INSERT INTO Paises VALUES ('Roménia','RO','ROU','642')
INSERT INTO Paises VALUES ('Ruanda','RW','RWA','646')
INSERT INTO Paises VALUES ('Rússia','RU','RUS','643')
INSERT INTO Paises VALUES ('Saara Ocidental','EH','ESH','732')
INSERT INTO Paises VALUES ('Samoa Americana','AS','ASM','016')
INSERT INTO Paises VALUES ('Samoa (Samoa Ocidental)','WS','WSM','882')
INSERT INTO Paises VALUES ('Saint Pierre et Miquelon','PM','SPM','666')
INSERT INTO Paises VALUES ('Salomão, Ilhas','SB','SLB','090')
INSERT INTO Paises VALUES ('São Cristóvão eévis (Saint Kitts eevis)','KN','KNA','659')
INSERT INTO Paises VALUES ('San Marino','SM','SMR','674')
INSERT INTO Paises VALUES ('São Tomé e Príncipe','ST','STP','678')
INSERT INTO Paises VALUES ('São Vicente e Granadinas','VC','VCT','670')
GO		
INSERT INTO Paises VALUES ('Santa Helena','SH','SHN','654')
INSERT INTO Paises VALUES ('Santa Lúcia','LC','LCA','662')
INSERT INTO Paises VALUES ('Senegal','SN','SEN','686')
INSERT INTO Paises VALUES ('Serra Leoa','SL','SLE','694')
INSERT INTO Paises VALUES ('Sérvia','RS','SRB','688')
INSERT INTO Paises VALUES ('Seychelles','SC','SYC','690')
INSERT INTO Paises VALUES ('Singapura','SG','SGP','702')
INSERT INTO Paises VALUES ('Síria','SY','SYR','760')
INSERT INTO Paises VALUES ('Somália','SO','SOM','706')
INSERT INTO Paises VALUES ('Sri Lanka','LK','LKA','144')
INSERT INTO Paises VALUES ('Suazilândia','SZ','SWZ','748')
INSERT INTO Paises VALUES ('Sudão','SD','SDN','736')
INSERT INTO Paises VALUES ('Suécia','SE','SWE','752')
INSERT INTO Paises VALUES ('Suíça','CH','CHE','756')
INSERT INTO Paises VALUES ('Suriname','SR','SUR','740')
INSERT INTO Paises VALUES ('Svalbard e Jan Mayen','SJ','SJM','744')
INSERT INTO Paises VALUES ('Tailândia','TH','THA','764')
INSERT INTO Paises VALUES ('Taiwan','TW','TWN','158')
INSERT INTO Paises VALUES ('Tajiquistão','TJ','TJK','762')
INSERT INTO Paises VALUES ('Tanzânia','TZ','TZA','834')
INSERT INTO Paises VALUES ('Terras Austrais e Antárticas Francesas (TAAF)','TF','ATF','260')
INSERT INTO Paises VALUES ('Território Britânico do Oceano Índico','IO','IOT','086')
INSERT INTO Paises VALUES ('Timor-Leste','TL','TLS','626')
INSERT INTO Paises VALUES ('Togo','TG','TGO','768')
INSERT INTO Paises VALUES ('Toquelau','TK','TKL','772')
INSERT INTO Paises VALUES ('Tonga','TO','TON','776')
INSERT INTO Paises VALUES ('Trindade e Tobago','TT','TTO','780')
INSERT INTO Paises VALUES ('Tunísia','TN','TUN','788')
INSERT INTO Paises VALUES ('Turks e Caicos','TC','TCA','796')
INSERT INTO Paises VALUES ('Turquemenistão','TM','TKM','795')
INSERT INTO Paises VALUES ('Turquia','TR','TUR','792')
INSERT INTO Paises VALUES ('Tuvalu','TV','TUV','798')
INSERT INTO Paises VALUES ('Ucrânia','UA','UKR','804')
INSERT INTO Paises VALUES ('Uganda','UG','UGA','800')
INSERT INTO Paises VALUES ('Uruguai','UY','URY','858')
INSERT INTO Paises VALUES ('Usbequistão','UZ','UZB','860')
INSERT INTO Paises VALUES ('Vanuatu','VU','VUT','548')
INSERT INTO Paises VALUES ('Vaticano','VA','VAT','336')
INSERT INTO Paises VALUES ('Venezuela','VE','VEN','862')
INSERT INTO Paises VALUES ('Vietname','VN','VNM','704')
INSERT INTO Paises VALUES ('Virgens Americanas, Ilhas','VI','VIR','850')
INSERT INTO Paises VALUES ('Virgens Britânicas, Ilhas','VG','VGB','092')
INSERT INTO Paises VALUES ('Wallis e Futuna','WF','WLF','876')
INSERT INTO Paises VALUES ('Zâmbia','ZM','ZMB','894')
INSERT INTO Paises VALUES ('Zimbabwe','ZW','ZWE','716')